project_id = "dgwmwmofyaxstykwuzxh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.debug-card-history]
    verify_jwt = false
  [functions.query-external-db]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
